### ISSUE TITLE
Multiple elm  projects in Open Folder

### ISSUE THREAD

**Issue by allanderek** [elm-tooling/elm-language-client-vscode#8] opened 2019-07-04 14:16 UTC
I have a project P that has two Elm sub-projects, E1 and E2. If I open the folder of the containing project P, then one of the two Elm sub-projects doesn't have symbols associated with each of the files therein.

This means that the outline does not work and `Ctrl+Shift+O` does not work.

Opening either sub-project as a folder itself means that all symbols are collected properly and everything works as expected.

**Comment by buinauskas** [comment] 2019-07-09 19:24
The issue is caused by this line: https://github.com/elm-tooling/elm-language-server/blob/c4cda7b9694cb9b405d6cfdf598cb44340b2f8d3/src/providers/astProvider.ts#L33


``` typescript
    this.connection.console.info(
      `Changed text document, going to parse it. ${params.textDocument.uri}`,
    );
    const document: VersionedTextDocumentIdentifier = params.textDocument;
    let tree: Tree | undefined = this.forest.getTree(document.uri);
    if (tree === undefined) {
      const fileContent: string = readFileSync(document.uri, "utf8");
      tree = this.parser.parse(fileContent);
    }
```

Code attempts to read file with `file://` prefix and this seems to be redundant on a Linux system and causes`readFileSync` ENOENT exception that it couldn't find a file.

A very dirty solution is to string replace `file://` with an empty string:
``` typescript
    this.connection.console.info(
      `Changed text document, going to parse it. ${params.textDocument.uri}`,
    );
    const document: VersionedTextDocumentIdentifier = params.textDocument;
    const correctPath = document.uri.replace("file://", "");
    let tree: Tree | undefined = this.forest.getTree(correctPath);
    if (tree === undefined) {
      const fileContent: string = readFileSync(correctPath, "utf8");
      tree = this.parser.parse(fileContent);
    }
```

While that works - it's hella crap solution.

**Comment by Razzeee** [comment] 2019-07-09 22:12
@buinauskas 
That was helpful for tracking it down. 

We start a server for each elm project and you can attach to each one via a different port. What happend here is that server number 1 was receiving updates on server number 2's files. That seemed to cause problems and was in fact not intended.
https://github.com/elm-tooling/elm-language-server/commit/1f605264e40d6b4e4ef5cc8b01740889dfa40ecd should fix that.

**Comment by Razzeee** [comment] 2019-07-12 18:36
Fixed in master, will be in the next release.

**Closed by Razzeee** 2019-07-12 18:36 UTC
