### ISSUE TITLE
Error not cleared when file is saved 

### ISSUE THREAD

**Issue by mattxo** [elm-tooling/elm-language-client-vscode#123] opened 2020-10-25 15:11 UTC
I installed the extension (v1.5.2), copied and pasted this into Main.elm

```
module Main exposing (..)

-- Press buttons to increment and decrement a counter.
--
-- Read how it works:
--   https://guide.elm-lang.org/architecture/buttons.html
--

import Browser
import Html exposing (Html, button, div, text)
import Html.Events exposing (onClick)
import Html.Attributes exposing (..)

-- MAIN

main : Program () Model Msg
main = Browser.sandbox { init = init, update = update, view = view }    

-- MODEL

type alias Model = Int

init : Model
init =
  0

-- UPDATE

type Msg
  = Increment
  | Decrement

update : Msg -> Model -> Model
update msg model =
  case msg of
    Increment ->
      model + 1

    Decrement ->
      model - 1

-- VIEW

view : Model -> Html Msg
view model =
    div []
    [ button [ class "red", onClick Decrement ] [ text "-" ]
    , div [] [ text (String.fromInt model) ]
    , button [ onClick Increment ] [ text "+" ]    
    ]
```

into VSCode, then changed ```button [ onClick Increment ] [ text "+" ]``` to ```button [ onClick Incrementx ] [ text "+" ]``` to induce an error, which works as expected. However, changing the line back and saving still leaves the line underlined in red and the old error message still in the Problems tab of VSCode.
 
![image](https://user-images.githubusercontent.com/6966145/97110937-80a1cb00-170e-11eb-9ab2-734ca1a76890.png)

## Expected Behavior
The error message should disappear.

## Current Behavior
The error message does not disappear.

I tested this with ```elm-spa-example-master``` as well but couldn't replicate the error. 

## Steps to Reproduce (for bugs)
1. Install extension
2. Copy above code into editor
3. Change line 49 to  ```button [ onClick Incrementx ] [ text "+" ]```
4. Save the file
5. Revert line 49 to ```button [ onClick Increment ] [ text "+" ]```
6. Save the file

## Context
I'm starting a new job and ELM is part of the stack. Hard to learn the language when the IDE is telling me lies!

## Your Environment

* Version used: elmtooling.elm-ls-vscode 1.5.2
* Editor name and version (e.g. VSCode 1.36.1): 
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

* Environment name and version (e.g. node.js 5.4): As above
* Operating System and version: As above

**Comment by Razzeee** [comment] 2020-10-25 16:37
I can't get that to happen and I would be surprised, if this was os based (running linux atm).

Anything you might have not mentioned?

**Comment by mattxo** [comment] 2020-10-25 21:30
I don’t *think* so. I did initially call the Main.elm file main.elm, and it complained about the casing, so I renamed the file. I also did have the deprecated vscode extension installed, though I removed it, reloaded vscode, installed the new version, restarted the lappy but to no avail. I tried changing the elm-analyze setting from never to on save and on change but that didn’t do anything except stop vscode presenting errors completely. 

I don’t have any quirky extensions installed, and it does work with the spa app example so I’m at a loss to what the issue is. The config json appears identical except for the dependencies so... yeah :/ 

I haven’t tried copy/pasting my code into the spa project (and deleting the obsolete stuff) so I guess I’ll try that unless there’s some other debug info I can give to help? 

VSCode does report any new errors (eg changing the definition to be ‘Decrementy’ for example, but if I fix those errors it just will not clear the last one it finds :/

**Comment by Razzeee** [comment] 2020-10-25 23:46
Is that an example project that you might be able to share?

**Comment by mattxo** [comment] 2020-10-26 06:49
Sure :) Here's a zip but let me know if it's easier to stick in a repo :) 

[elm.zip](https://github.com/elm-tooling/elm-language-client-vscode/files/5437259/elm.zip)

**Comment by ymtszw** [comment] 2020-10-26 13:17
Cannot say it is exactly the same issue, but the similar symptom is happening to me.

Seemingly it breaks when the compilation errors get "updated", i.e., errors still happening but on different places (especially on different files).
If all errors are resolved, problem list is cleared too, but until then, already resolved error messages are lingering on problem list. At least that is my observation.

Will try to prove or disprove this by small example if I got time. Kind of busy for a couple days.

**Comment by Razzeee** [comment] 2020-10-28 01:19
@mattxo I fail to get this to reproduce with the zip file you've posted. At this point it might be easiest to have a look by your own. https://github.com/elm-tooling/elm-language-client-vscode#contributing--debugging should be a good startingpoint. 

The relevant logic would be in `diagnosticProvider.ts`.

**Comment by mattxo** [comment] 2020-10-28 18:57
It'll be a bit of a learning curve for me (never messed with VSCode extensions before) but I'll have a look :)

**Comment by Razzeee** [comment] 2020-10-29 00:19
Let me know, if you need any help.

**Comment by whitecolor** [comment] 2020-10-30 15:47
I have the same issue. It seems there are some problems in the logic and tests are definitely lacking.

**Comment by whitecolor** [comment] 2020-10-30 22:00
Found the reason for my error https://github.com/elm-tooling/elm-language-client-vscode/issues/129

**Comment by Razzeee** [comment] 2020-11-07 15:08
This should be fixed with the version from yesterday.

**Closed by Razzeee** 2020-11-07 15:08 UTC
