### ISSUE TITLE
Folding regions are messed up

### ISSUE THREAD

**Issue by annaghi** [elm-tooling/elm-language-client-vscode#28] opened 2019-08-31 11:23 UTC
Folding regions are messed up

## Expected Behavior
Would like to use the folding shortcut keys described here https://code.visualstudio.com/docs/editor/codebasics#_folding

The folded functions are separated by newlines.
All the gutters are visible within a function.

![VSCode-expected](https://user-images.githubusercontent.com/8246853/64063078-b40ec580-cbef-11e9-87cc-7567283e9f89.gif)

## Current Behavior

The folded functions are too close to each other, cannot see the type annotations.
There are missing gutters and no folding within a function.

![VSCode-messy](https://user-images.githubusercontent.com/8246853/64063102-2bdcf000-cbf0-11e9-817f-0b187672f12f.gif)

## Possible Solution
Sorry, do not know what would be the solution.

## Steps to Reproduce (for bugs)
1. Open an `elm` file
2. Fold all first level regions with `Ctrl+k Ctrl+1`
3. Unfold a function with some nested structure by clicking on the gutter
4. Position the cursor inside that function
5. Fold all third level regions within that function with `Ctrl+k Ctrl+3`

## Context

I heavily rely on folding because it helps me to see the bigger picture of an Elm file. When working on a huge file I usually start with folding all functions and types, and unfold only those which are needed at the time.

## Your Environment

* Version used: 0.5.2
* Editor name and version: VS Code 1.37.1
* Environment name and version: nodejs 10.16.3
* Operating System and version: Ubuntu 18.04.3

**Comment by Razzeee** [comment] 2019-08-31 21:33
I pushed an update to the development version of the server, branches of case statements should fold fine with that. https://github.com/elm-tooling/elm-language-server/commit/dfec6212d5a9c0c5449b378df200c4070221ffd4

If you can think of more tokens, where you think that they need to fold, let me know. We only added a basic set, when we started out.

The other problems are deeper.

1. Let/in & if/then/else should fold. But the ast that we're action on is not build for that. I will look into changing it.

2. Function level folding is weird, when there is a function, that has a comment (or well docs) on it. That's also caused by the parser, not knowing where to end the function before and thinking it might just be a comment, that's still inside that's functions body. Probably fixable in the parser, but also probably time consuming to get right.

**Comment by Razzeee** [comment] 2019-09-01 15:13
I was able to fix the outstanding problems, this change will be included in the next release. Not sure when that will be, as we might need some testing.

**Closed by Razzeee** 2019-09-01 15:13 UTC
