### ISSUE TITLE
Support code comments in the outline view

### ISSUE THREAD

**Issue by Kurren123** [elm-tooling/elm-language-client-vscode#101] opened 2020-04-28 10:23 UTC
**Edit:** I realise this first needs to be implemented upstream so I made [this issue](https://github.com/elm-tooling/elm-language-server/issues/264) and will get back to this current one after.

I've read in a few places that it's not unusual for Elm files to be long. To me this means that the outline view needs to be used more for navigation than a language with typically shorter files. I have seen the NoRedInk guys suggest using comments to help with navigation. Eg in the [elm guide](https://guide.elm-lang.org/architecture/buttons.html), we have code like this:

```elm
import Browser
import Html exposing (Html, button, div, text)
import Html.Events exposing (onClick)



-- MAIN


main =
  Browser.sandbox { init = init, update = update, view = view }



-- MODEL

type alias Model = Int

init : Model
init =
  0


-- UPDATE
```

... and so on. I would suggest a setting in vscode where we can specify a regex for single line comments, and if a comment matches this regex then the comment appears as a "folder" in the outline view and every symbol under the comment goes under the folder (until the next "folder" comment is found).By default this regex can be set to anything will all caps, to match the convention already out there. So the example above would give an outline view of:

```
file
    MAIN
        main
    MODEL
        Model
        init
    UPDATE
```

I would be happy to try and make this happen. Please let me know if this ticket should be made upstream and I'll close the issue.

Thanks

**Comment by Razzeee** [comment] 2020-04-28 18:04
I'm a bit confused by this, what exactly are you trying to solve? Just grouping the elm architecture in the outline?

I think the problem is, that there is no specific syntax for this and most people will end up with those groups by mistake. And it might not be very obvious, how they ended up there to them.

**Comment by Kurren123** [comment] 2020-04-28 20:41
@Razzeee the problem I’m trying to solve is to make long files easier to navigate. Not necessarily the elm architecture, but when people use comments to group “regions” of code together in a long file as suggested by many of the elm authors. They typically do this by having a single line comment in all caps. I agree that users may do this by mistake so maybe have it as an opt-in option?

**Comment by Razzeee** [comment] 2020-04-29 00:54
Regions in general are kind of a no-go for me, coming from C#. But if this can get support in the community, I won't be blocking this. :)

Btw, I'm not convinced, that it would improve navigation. As I would suggest to use "go to symbol in editor/workspace" for that. It might help with discovery, if your new in a codebase, if the author maintained the regions correctly.

**Comment by Razzeee** [comment] 2020-05-24 12:48
Closing as this is being discussed in https://github.com/elm-tooling/elm-language-server/issues/264

**Closed by Razzeee** 2020-05-24 12:48 UTC
