### ISSUE TITLE
Multiple project folder error: Can't find file for formatting.

### ISSUE THREAD

**Issue by allanderek** [elm-tooling/elm-language-client-vscode#30] opened 2019-09-13 12:04 UTC
I'm very sorry but I haven't been able to workout the reasons or situations under which this happens.

I have a multiple project folder, which has two elm projects in `commerce` and `admin` subdirectories. The plugin appears to work well when in the `commerce` sub-directory. When in the `admin` sub-directory everything starts up well and I get warnings/errors as expected. However, as soon as I save a file, I get an error in the `output` log as:

`[Error - 12:48:10] Can't find file for formatting.`

After that nothing seems to work, formatting is done, but also warnings and errors are not updated.

Everything seems to work fine if I open only the `admin` folder in VSCode.

## Expected Behavior

The plugin continue to work after the file is saved.

## Current Behavior

It stops working after a file is saved.

## Possible Solution

Hmm, sorry, no idea.

## Steps to Reproduce (for bugs)

As I said, I'm very sorry but I really cannot provide any additional information that may help solve this. I'll report back in this issue if I discover something.

One extra piece of information. Both projects (in `commerce` and `admin` sub-directories) have some 'sub-directories' in common, in particular they both have modules in `src/Types/` and `src/Components`, so my first thought was that perhaps the plugin is looking for `admin/src/Components/Module.elm` in `commerce/src/Components/Module.elm`. However, they both have a couple of module names say `admin/src/Components/Common.elm` and `commerce/src/Components/Common.elm`, and if I save the former I get the same error (`[Error - 12:48:10] Can't find file for formatting.`) as before, when I might have expected it to find the file albeit format the wrong one.

## Context

Nothing special I can think of, other than that the open folder houses two separate elm projects. 

## Your Environment

* Version used: ElmLS 0.6.0
* Editor name and version (e.g. VSCode 1.36.1): VSCode 1.37.1
* Environment name and version (e.g. node.js 5.4): npm 6.11.2
* Operating System and version:Manjaro Linux 18.4

**Comment by Razzeee** [comment] 2019-09-13 23:22
Are both actual 0.19.0 projects?

**Comment by allanderek** [comment] 2019-09-14 08:15
Yes, sorry, both are 0.19.0 projects.

**Comment by Razzeee** [comment] 2019-09-16 11:39
I think I found and fixed the underlying problem (currently in a branch) but it also helped me to see some more problems, that are connected to multiple elmWorkspaces in one vscode workspace. So I will have to keep working on this some more.

**Comment by allanderek** [comment] 2019-09-16 13:46
Okay that's great news. It's not an urgent show-stopper for me, I've just opened the two separate projects as two separate workspaces.

**Comment by julian-jelfs** [comment] 2019-12-18 11:02
Same problem for me. The only reason I add a comment is that I similar behaviour when using the elm language server integration with nvim using coc. I was wondering whether that might point to a problem in the language server implementation itself rather than the vscode plugin?

**Comment by Razzeee** [comment] 2019-12-18 11:38
I'm not sure. As far as I understood, separating projects like this is how it's meant to be. CoC should (somehow) know that it needs to spin up multiple servers too.

If I got that wrong and we're meant to only have one server running, we need to redesign a bunch of things in the server. And I would have questions about the protocol, I previously was not able to resolve.

**Comment by sentience** [comment] 2019-12-24 06:52
We've just finally upgraded the last of our Elm 0.18 code here at Culture Amp, so we have a bunch of engineers eager to switch to this new editor extension. Unfortunately, in my testing, we're falling pretty to issues like these that seem related to having more than one elm.json root in a single VSCode workspace.

Is there any way I can help, @Razzeee?

**Comment by Razzeee** [comment] 2019-12-24 13:52
But your case also is that each subdirectory has a elm.json and there is none at the root?

Feel free to look at the code. It seems the branch I talked about earlier is https://github.com/elm-tooling/elm-language-server/tree/improve-elm-workspaces but it has been quiet some time and I would likely start from scratch.

**Comment by Razzeee** [comment] 2019-12-24 14:11
You might also be able to get around this problem using vscode workspaces https://code.visualstudio.com/docs/editor/multi-root-workspaces

From a quick test it seems to work fine. But you will have to take a deeper look.

**Comment by sentience** [comment] 2019-12-25 00:49
@Razzeee That's right. No elm.json at the root of my VSCode workspace, but 27 of them nested in various subfolders. Perhaps importantly, some of our Elm files are in folders with no elm.json file in a parent directory, because they are shared modules that are imported by one (or more!) of our Elm applications that do have elm.json files.

For example:

```
|
|- apps
|  |- app1
|  |  |- elm.json (includes '../../lib' in its srcdirs)
|  |  `- App1.elm (imports Lib.elm)
|  `- app2
|     |- elm.json (includes '../../lib' in its srcdirs)
|     `- App2.elm (imports Lib.elm)
`- lib
   ` Lib.elm
```

Unfortunately breaking up our project into 27 separate workspaces (and getting all of our engineers to update their workspaces whenever we add a new one) would be somewhat impractical.

I'll take a look at the code and see if I have any ideas.

**Comment by Razzeee** [comment] 2019-12-25 09:07
I think workspaces are just files that can be checked in. So they should be
shareable.
Still a solution that works for non vscode folks is preferable.

**Comment by sentience** [comment] 2019-12-30 06:35
I've spent a couple of hours learning about the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/), getting a debuggable copy of elm-language-client-vscode and elm-language-server running on my machine, and tracing source code for how the document formatting request is handled.

I haven't fully gotten my head around the layers of indirection, but here's what I've understood so far:

The `Server` at startup creates an `ElmWorkspace` for each elm.json file it finds in your project's directory tree. Each `ElmWorkspace` finds all ***.elm** files in the `"source-directories"` specified in the elm.json file, and follows the `import` statements they contain to also find all dependencies in **elm-stuff** and other directories.

It then registers each ***.elm** file, with a bunch of ”providers”, one for each major feature of the language server (e.g. the `DocumentFormattingProvider` for requests to format the document). I haven't yet found how the files get registered with the providers, but it seems to have something to do with `TextDocumentEvents`, which listens for `"open"` events (among others) for text documents.

When a request to format a document comes in, the request is supposed to be routed to an instance of `DocumentFormattingProvider` with a reference to a `TextDocumentEvents` object that knows about that specific document. In my debugging, all of my Elm files have their requests routed to a `DocumentFormattingProvider` that has an _empty_ collection of documents! Why that is, I haven't yet been able to figure out.

I can see that on [your WIP branch](https://github.com/elm-tooling/elm-language-server/tree/improve-elm-workspaces) you're doing some rewrites of how the `DocumentFormattingProvider` is found when a document formatting request comes in. I don't yet understand the old mechanisms enough to see how your new approach differs, though.

One hunch I now have after all this debugging is that a quirk of my **elm.json** files may be responsible for most of the language server features not working for me: While a stereotypical **elm.json** file starts with `"source-directories": [ "src" ]` (Elm files in a **src** subdirectory), all of our **elm.json** files start with `"source-directories": [ "." ]` (Elm files in the root directory). When the Elm Language Server starts up, it reports all of our source files with `/./` in the path (e.g. “Adding /Users/kyank/code/murmur/app/client/modules/ca-workflow-header/./WorkflowHeader/Decoders.elm”). And because many of our **elm.json** files refer to shared library directories whose paths begin with `../../`, I see plenty of `/../` in the reported source file paths, too (e.g. “Adding /Users/kyank/code/murmur/app/client/modules/ca-workflow-header/../../../../lib/client/modules/ca-ui/ProgressDialog.elm”).

Is it possible that all of our source files are getting registered in the server with these “non-canonical” paths, so that when the client later sends a request for a path like `/Users/kyank/code/murmur/app/client/modules/ca-workflow-header/WorkflowHeader/Decoders.elm` (without the `/./`), the server is unable to match it to any of its registered files? If so, might there be a possible fix of ensuring that the server uses `path.resolve` to resolve all of the source file paths to absolute, canonical paths before registering them?

**Comment by sentience** [comment] 2019-12-30 06:55
I did some more tracing for hover requests (which are also not working in our multi-workspace project), and found that something similar is happening there: the hover request gets routed to a `HoverProvider` that contains a `forest` that does not include the file, and therefore the request is ignored.

I've experimented with hacking in a `path.resolve(…)` at the right place to register all files with normalized paths, but that hasn't made any difference to the behaviour for me.

**Comment by sentience** [comment] 2019-12-30 07:09
OK, I think I have an idea of what's going on. Once each `ElmWorkspace` finds all of the ***.elm** files that it contains (and their dependencies), it records these in a “tree”. When the `Server` is told that all of the trees have been built, it calls `registerInitializedProviders` on each `ElmWorkspace`, which creates a set of providers. Each of those providers registers one or more event handlers on the `connection`, like this:

https://github.com/elm-tooling/elm-language-server/blob/88e5021e88b7861a9beefa6e5ecfdffeda401c64/src/providers/documentFormatingProvider.ts#L19

and this:

https://github.com/elm-tooling/elm-language-server/blob/88e5021e88b7861a9beefa6e5ecfdffeda401c64/src/providers/hoverProvider.ts#L20

The problem is, there's only one `connection` and multiple `ElmWorkspace` instances, and each call to `onDocumentFormatting` or `onHover` replaces any previously-registered handler with the new one. As a result, only the last `ElmWorkspace`'s handlers actually remain registered!

I think the fix here will be to write a set of `on*` handlers that in turn call the corresponding handlers for all of the active `ElmWorkspace`s. Unless you have any better ideas, I'm happy to get started on a prototype of this!

**Comment by Razzeee** [comment] 2019-12-30 09:37
Yes, that's essentially, what my branch tried to do.

Nice job on understanding the code so far.

**Comment by sentience** [comment] 2020-01-01 13:49
Feel free to assign this to me. I'm planning to submit a fix in the next few days.

**Comment by sentience** [comment] 2020-01-03 02:44
As I suspect @Razzeee may have predicted, this is a bigger job than I was expecting! Processing every client event in _all_ detected workspaces, trusting that only one of them will actually do anything, is looking like it will generate too many potential problems. 

This is more properly tracked as an issue of the language server (specifically, it looks like elm-tooling/elm-language-server#187 was already created for this). I'm going to start posting updates on my work there.

**Comment by sentience** [comment] 2020-01-09 12:58
See tooling/elm-language-server#187 if anyone is wanting to test out an early version of a fix!

**Comment by Razzeee** [comment] 2020-01-28 09:57
Has been merged and released

**Closed by Razzeee** 2020-01-28 09:57 UTC
Labels: bug, help wanted
